/**
 * Store locations for Bad Boy Golf Carts.
 *
 * Single source of truth for every geo-targeted SEO artifact: geo-sitemap.xml,
 * locations.json / .geojson / .kml, the per-store JSON-LD in /schema, and the
 * location sections of llms-full.txt. Verified store data - keep addresses and
 * coordinates in sync with the DMS store records.
 */

export interface StoreLocation {
  slug: string;
  storeName: string;
  street: string;
  city: string;
  state: string;
  stateCode: string;
  zip: string;
  county: string;
  lat: number;
  lng: number;
  region: string;
  metro: string;
  dma: string;
  serviceRadius: string;
  population: string;
  targetMarkets: string;
  landmarks: string;
  interstate: string;
  nearbyCities: string[];
  nearbyCounties: string[];
  keywords: string[];
}

export const STORE_LOCATIONS: StoreLocation[] = [
  {
    slug: "hatfield",
    storeName: "Bad Boy Golf Carts - Hatfield",
    street: "2333 Bethlehem Pike",
    city: "Hatfield",
    state: "Pennsylvania",
    stateCode: "PA",
    zip: "19440",
    county: "Montgomery County",
    lat: 40.2751,
    lng: -75.2993,
    region: "Greater Philadelphia / Southeastern Pennsylvania",
    metro: "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA",
    dma: "Philadelphia DMA",
    serviceRadius: "50+ miles",
    population: "6,000,000+ (Greater Philadelphia Metro)",
    targetMarkets: "Suburban neighborhoods, golf communities, retirement communities, campgrounds",
    landmarks: "Philadelphia (25 mi), Valley Forge National Historical Park (15 mi), Bucks County, Lehigh Valley, King of Prussia Mall",
    interstate: "PA Turnpike (I-276), I-476 (Blue Route), Route 309, Route 202",
    nearbyCities: ["Lansdale", "North Wales", "Souderton", "Quakertown", "Doylestown", "Chalfont", "Harleysville", "Telford", "Perkasie", "Sellersville", "Ambler", "Blue Bell", "Norristown", "King of Prussia", "Plymouth Meeting", "Collegeville", "Phoenixville", "Conshohocken", "Fort Washington", "Warminster", "Horsham", "Montgomery Township", "Warrington", "New Britain", "Skippack", "Schwenksville", "Pottstown", "Spring House", "Dresher", "Abington"],
    nearbyCounties: ["Montgomery", "Bucks", "Chester", "Delaware", "Philadelphia", "Lehigh", "Northampton", "Berks"],
    keywords: ["golf carts hatfield pa", "golf cart dealer montgomery county", "golf carts philadelphia area", "golf carts near me hatfield", "buy golf cart hatfield pa", "golf cart dealer philadelphia suburbs", "golf carts bucks county", "golf carts king of prussia area"],
  },
  {
    slug: "ocean-view",
    storeName: "Bad Boy Golf Carts - Ocean View",
    street: "101 NJ-50",
    city: "Ocean View",
    state: "New Jersey",
    stateCode: "NJ",
    zip: "08230",
    county: "Cape May County",
    lat: 39.2482,
    lng: -74.7202,
    region: "South Jersey Shore / Cape May Peninsula",
    metro: "Ocean City, NJ MSA",
    dma: "Philadelphia DMA",
    serviceRadius: "40+ miles",
    population: "500,000+ (Cape May & Atlantic County region)",
    targetMarkets: "Shore communities, vacation homes, 55+ communities, campgrounds, retirement villages",
    landmarks: "Jersey Shore, Atlantic City (20 mi), Cape May (15 mi), Wildwood Boardwalk (10 mi), Ocean City Boardwalk",
    interstate: "Garden State Parkway, Route 9, Route 50, Atlantic City Expressway",
    nearbyCities: ["Sea Isle City", "Ocean City", "Avalon", "Stone Harbor", "Wildwood", "Cape May", "Strathmere", "Marmora", "Somers Point", "Northfield", "Linwood", "Egg Harbor Township", "Vineland", "Millville", "Bridgeton", "Hammonton", "Margate City", "Ventnor City", "Atlantic City", "Pleasantville", "Mays Landing", "Upper Township", "Dennis Township", "Woodbine"],
    nearbyCounties: ["Cape May", "Atlantic", "Cumberland", "Salem", "Gloucester"],
    keywords: ["golf carts ocean view nj", "golf carts cape may county", "golf carts jersey shore", "golf carts atlantic city area", "golf carts shore communities nj", "golf cart dealer south jersey", "golf carts sea isle city", "golf carts ocean city nj", "golf carts wildwood nj"],
  },
  {
    slug: "long-pond",
    storeName: "Bad Boy Golf Carts - Long Pond (Poconos)",
    street: "4738 PA-115",
    city: "Long Pond",
    state: "Pennsylvania",
    stateCode: "PA",
    zip: "18334",
    county: "Monroe County",
    lat: 41.0506,
    lng: -75.4532,
    region: "Pocono Mountains / Northeast Pennsylvania",
    metro: "East Stroudsburg, PA MSA",
    dma: "Wilkes-Barre/Scranton DMA",
    serviceRadius: "40+ miles",
    population: "300,000+ (Pocono Mountain region)",
    targetMarkets: "Resort communities, vacation properties, campgrounds, timeshares, 55+ communities",
    landmarks: "Pocono Raceway (adjacent), Camelback Mountain, Big Boulder, Jack Frost, Delaware Water Gap National Recreation Area, Bushkill Falls, Kalahari Resorts, Great Wolf Lodge",
    interstate: "I-80, I-380, Route 115, Route 940, Route 611",
    nearbyCities: ["Pocono Summit", "Blakeslee", "Tobyhanna", "Mount Pocono", "Tannersville", "Stroudsburg", "East Stroudsburg", "Bartonsville", "Pocono Pines", "Pocono Lake", "Brodheadsville", "Saylorsburg", "Sciota", "Cresco", "Mountainhome", "Buck Hill Falls", "Canadensis", "Swiftwater", "Analomink", "Delaware Water Gap", "Henryville", "Effort", "Gilbert", "Kresgeville", "Jim Thorpe"],
    nearbyCounties: ["Monroe", "Carbon", "Pike", "Wayne", "Northampton", "Luzerne"],
    keywords: ["golf carts poconos", "golf carts pocono mountains", "golf carts long pond pa", "golf carts monroe county pa", "golf cart dealer poconos", "golf carts mount pocono", "golf carts stroudsburg pa", "golf carts resort community poconos", "golf carts vacation property pa"],
  },
  {
    slug: "dover",
    storeName: "Bad Boy Golf Carts - Dover",
    street: "5158 N Dupont Hwy",
    city: "Dover",
    state: "Delaware",
    stateCode: "DE",
    zip: "19901",
    county: "Kent County",
    lat: 39.1582,
    lng: -75.5244,
    region: "Central Delaware / Delmarva Peninsula",
    metro: "Dover, DE MSA",
    dma: "Philadelphia DMA",
    serviceRadius: "50+ miles",
    population: "400,000+ (entire state of Delaware accessible)",
    targetMarkets: "Beach communities, retirement communities, military community (Dover AFB), state government area",
    landmarks: "Dover International Speedway, Delaware State Capitol, Dover Air Force Base, Delaware Beaches (45 mi), Bombay Hook National Wildlife Refuge",
    interstate: "Route 1, Route 13 (DuPont Highway), Route 8, Route 113",
    nearbyCities: ["Camden-Wyoming", "Smyrna", "Clayton", "Milford", "Harrington", "Felton", "Magnolia", "Frederica", "Woodside", "Hartly", "Cheswold", "Kenton", "Townsend", "Middletown", "Odessa", "Georgetown", "Seaford", "Laurel", "Bridgeville", "Lewes", "Rehoboth Beach", "Dewey Beach", "Bethany Beach", "Fenwick Island", "Milton", "Lincoln", "Ellendale"],
    nearbyCounties: ["Kent (DE)", "Sussex (DE)", "New Castle (DE)", "Caroline (MD)", "Queen Anne's (MD)", "Dorchester (MD)"],
    keywords: ["golf carts dover de", "golf carts delaware", "golf carts kent county de", "golf carts delaware beaches", "golf carts rehoboth beach area", "golf carts sussex county de", "golf cart dealer delaware", "golf carts smyrna de", "golf carts middletown de", "golf carts milford de", "golf carts lewes de"],
  },
  {
    slug: "scranton",
    storeName: "Bad Boy Golf Carts - Scranton",
    street: "1225 N. Keyser Ave #2",
    city: "Scranton",
    state: "Pennsylvania",
    stateCode: "PA",
    zip: "18504",
    county: "Lackawanna County",
    lat: 41.409,
    lng: -75.6624,
    region: "Northeastern Pennsylvania / Lackawanna Valley",
    metro: "Scranton--Wilkes-Barre, PA MSA",
    dma: "Wilkes-Barre/Scranton DMA",
    serviceRadius: "50+ miles",
    population: "600,000+ (Scranton-Wilkes-Barre Metro)",
    targetMarkets: "Residential neighborhoods, 55+ communities, campgrounds, lake communities",
    landmarks: "Steamtown National Historic Site, PNC Field, Montage Mountain, The Poconos, Tobyhanna Army Depot",
    interstate: "I-81, I-84, I-380, I-476 (PA Turnpike Extension), Route 6, Route 11",
    nearbyCities: ["Wilkes-Barre", "Dunmore", "Old Forge", "Carbondale", "Pittston", "Kingston", "Taylor", "Moosic", "Dickson City", "Clarks Summit", "Dalton", "Archbald", "Blakely", "Olyphant", "Throop", "Jessup", "Moscow", "Hamlin", "Honesdale", "Hawley", "Milford", "Montrose", "Tunkhannock", "Dallas", "Mountain Top", "Hazleton", "Bloomsburg"],
    nearbyCounties: ["Lackawanna", "Luzerne", "Wyoming", "Wayne", "Susquehanna", "Pike", "Monroe", "Columbia", "Schuylkill"],
    keywords: ["golf carts scranton pa", "golf carts wilkes barre", "golf carts northeast pa", "golf carts lackawanna county", "golf cart dealer scranton", "golf carts dunmore pa", "golf carts pittston pa", "golf carts clarks summit pa"],
  },
  {
    slug: "raleigh",
    storeName: "Bad Boy Golf Carts - Raleigh",
    street: "2700 South Wilmington Street",
    city: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    zip: "27603",
    county: "Wake County",
    lat: 35.7596,
    lng: -78.6382,
    region: "Research Triangle / Central North Carolina",
    metro: "Raleigh-Durham-Chapel Hill, NC CSA",
    dma: "Raleigh-Durham DMA",
    serviceRadius: "75+ miles",
    population: "2,000,000+ (Research Triangle Metro)",
    targetMarkets: "Golf communities, planned neighborhoods, retirement communities, university communities",
    landmarks: "Research Triangle Park, NC State University, Duke University, UNC Chapel Hill, PNC Arena, Pinehurst Resort, Carolina Hurricanes",
    interstate: "I-40, I-440, I-540, I-87, US-1, US-64, US-70, US-401",
    nearbyCities: ["Durham", "Chapel Hill", "Cary", "Apex", "Holly Springs", "Fuquay-Varina", "Wake Forest", "Garner", "Clayton", "Smithfield", "Knightdale", "Wendell", "Zebulon", "Sanford", "Pittsboro", "Hillsborough", "Mebane", "Burlington", "Henderson", "Goldsboro", "Wilson", "Rocky Mount", "Fayetteville", "Southern Pines", "Pinehurst", "Aberdeen", "Morrisville", "Rolesville", "Youngsville", "Franklinton", "Oxford"],
    nearbyCounties: ["Wake", "Durham", "Orange", "Chatham", "Johnston", "Harnett", "Lee", "Franklin", "Granville", "Nash", "Wayne", "Sampson", "Moore", "Vance", "Person", "Alamance"],
    keywords: ["golf carts raleigh nc", "golf carts research triangle", "golf carts durham nc", "golf carts chapel hill nc", "golf carts cary nc", "golf carts wake county nc", "golf carts pinehurst nc", "golf carts southern pines nc", "golf carts fayetteville nc", "golf cart dealer triangle nc", "golf carts apex nc", "golf carts holly springs nc", "golf carts fuquay varina nc"],
  },
  {
    slug: "south-bend",
    storeName: "Bad Boy Golf Carts - South Bend",
    street: "52129 State Highway 933",
    city: "South Bend",
    state: "Indiana",
    stateCode: "IN",
    zip: "46637",
    county: "St. Joseph County",
    lat: 41.7002,
    lng: -86.239,
    region: "Michiana / Northern Indiana",
    metro: "South Bend-Mishawaka, IN-MI MSA",
    dma: "South Bend-Elkhart DMA",
    serviceRadius: "60+ miles",
    population: "800,000+ (Michiana region, spans IN/MI border)",
    targetMarkets: "University community, suburban neighborhoods, lake communities, Amish country, retirement communities",
    landmarks: "University of Notre Dame, Studebaker National Museum, Amish Country (Elkhart/Goshen), Indiana Dunes (60 mi), Warren Dunes (MI)",
    interstate: "I-80/I-90 (Indiana Toll Road), US-31, US-20, US-33, State Road 933",
    nearbyCities: ["Mishawaka", "Elkhart", "Goshen", "Granger", "Niles MI", "Buchanan MI", "Dowagiac MI", "Plymouth", "Warsaw", "LaPorte", "Michigan City", "Valparaiso", "Bremen", "Nappanee", "Middlebury", "Benton Harbor MI", "St. Joseph MI", "Berrien Springs MI", "Cassopolis MI", "Edwardsburg MI", "Osceola", "Wakarusa", "Syracuse"],
    nearbyCounties: ["St. Joseph (IN)", "Elkhart (IN)", "Marshall (IN)", "Kosciusko (IN)", "LaPorte (IN)", "Starke (IN)", "Pulaski (IN)", "Fulton (IN)", "Cass (IN)", "Berrien (MI)", "Cass (MI)", "Van Buren (MI)"],
    keywords: ["golf carts south bend in", "golf carts mishawaka in", "golf carts elkhart in", "golf carts goshen in", "golf carts northern indiana", "golf carts michiana", "golf carts notre dame area", "golf carts st joseph county in", "golf cart dealer indiana", "golf carts granger in", "golf carts niles michigan"],
  },
  {
    slug: "gloucester-point",
    storeName: "Bad Boy Golf Carts - Gloucester Point",
    street: "2810 George Washington Memorial Highway",
    city: "Gloucester Point",
    state: "Virginia",
    stateCode: "VA",
    zip: "23072",
    county: "Gloucester County",
    lat: 37.2779,
    lng: -76.4966,
    region: "Hampton Roads / Virginia Peninsula",
    metro: "Virginia Beach-Norfolk-Newport News, VA-NC MSA",
    dma: "Norfolk-Portsmouth-Newport News DMA",
    serviceRadius: "50+ miles",
    population: "1,800,000+ (Hampton Roads Metro)",
    targetMarkets: "Military community, coastal/waterfront living, retirement communities, golf communities, historic area tourism",
    landmarks: "Colonial Williamsburg, Yorktown Battlefield, Virginia Institute of Marine Science, Chesapeake Bay, Busch Gardens, Water Country USA, Joint Base Langley-Eustis, Naval Station Norfolk",
    interstate: "I-64, Route 17, Route 14, Colonial Parkway",
    nearbyCities: ["Yorktown", "Williamsburg", "Newport News", "Hampton", "Norfolk", "Virginia Beach", "Chesapeake", "Poquoson", "Mathews", "West Point", "Tappahannock", "Kilmarnock", "Urbanna", "Saluda", "Deltaville", "Topping", "Gloucester Courthouse", "Hayes", "Achilles", "Suffolk", "Portsmouth", "James City", "Smithfield", "Surry"],
    nearbyCounties: ["Gloucester", "York", "James City", "Mathews", "Middlesex", "King and Queen", "King William", "New Kent", "Charles City", "Isle of Wight", "Surry", "Williamsburg (independent city)"],
    keywords: ["golf carts gloucester va", "golf carts hampton roads", "golf carts williamsburg va", "golf carts newport news va", "golf carts hampton va", "golf carts norfolk va", "golf carts virginia beach va", "golf carts yorktown va", "golf carts chesapeake bay area", "golf cart dealer hampton roads", "golf carts virginia peninsula", "golf carts tidewater virginia"],
  },
  {
    slug: "bayville-township",
    storeName: "Bad Boy Golf Carts - Bayville",
    street: "155 Atlantic City Boulevard",
    city: "Bayville Township",
    state: "New Jersey",
    stateCode: "NJ",
    zip: "08721",
    county: "Ocean County",
    lat: 39.9065,
    lng: -74.156,
    region: "Jersey Shore / Central New Jersey Coast",
    metro: "New York-Newark-Jersey City, NY-NJ-PA MSA (extended)",
    dma: "New York DMA (partial)",
    serviceRadius: "40+ miles",
    population: "600,000+ (Ocean County and surrounding areas)",
    targetMarkets: "55+ retirement communities, shore communities, vacation properties, campgrounds",
    landmarks: "Barnegat Bay, Island Beach State Park, Six Flags Great Adventure (30 mi), Seaside Heights Boardwalk, Point Pleasant Boardwalk, Jenkinson's Aquarium",
    interstate: "Garden State Parkway, Route 9, Route 37, Route 70",
    nearbyCities: ["Toms River", "Brick", "Lakewood", "Jackson", "Manchester", "Lacey", "Forked River", "Barnegat", "Beachwood", "Pine Beach", "Island Heights", "Seaside Heights", "Seaside Park", "Lavallette", "Ortley Beach", "Point Pleasant", "Bay Head", "Manasquan", "Long Beach Island", "Berkeley Township", "Stafford Township"],
    nearbyCounties: ["Ocean", "Monmouth", "Burlington", "Middlesex"],
    keywords: ["golf carts bayville nj", "golf carts ocean county nj", "golf carts toms river area", "golf carts 55+ communities nj", "golf carts retirement communities nj", "golf carts brick nj", "golf carts lakewood nj", "golf carts seaside nj", "golf carts jersey shore", "golf cart dealer ocean county"],
  },
  {
    slug: "ocean-township",
    storeName: "Bad Boy Golf Carts - Waretown",
    street: "526 U.S. 9",
    city: "Ocean Township (Waretown)",
    state: "New Jersey",
    stateCode: "NJ",
    zip: "08758",
    county: "Ocean County",
    lat: 39.7812,
    lng: -74.2035,
    region: "Southern Ocean County / Jersey Shore",
    metro: "New York-Newark-Jersey City, NY-NJ-PA MSA (extended)",
    dma: "New York DMA (partial)",
    serviceRadius: "35+ miles",
    population: "400,000+ (Southern Ocean County)",
    targetMarkets: "Long Beach Island vacation community, 55+ communities, beach homeowners, campgrounds",
    landmarks: "Long Beach Island, Edwin B. Forsythe National Wildlife Refuge, Bass River State Forest, Barnegat Lighthouse, Fantasy Island Amusement Park",
    interstate: "Garden State Parkway, Route 9, Route 72 (to Long Beach Island)",
    nearbyCities: ["Barnegat", "Manahawkin", "Stafford Township", "Long Beach Township", "Beach Haven", "Ship Bottom", "Surf City", "Harvey Cedars", "Barnegat Light", "Tuckerton", "Little Egg Harbor", "New Gretna", "Chatsworth", "Hammonton", "Galloway Township", "Port Republic", "Smithville", "Lacey Township", "Forked River", "West Creek"],
    nearbyCounties: ["Ocean", "Burlington", "Atlantic"],
    keywords: ["golf carts waretown nj", "golf carts long beach island", "golf carts barnegat nj", "golf carts manahawkin nj", "golf carts southern ocean county", "golf cart dealer waretown", "golf carts beach haven nj", "golf carts surf city nj", "golf carts stafford township nj"],
  },
  {
    slug: "lecanto",
    storeName: "Bad Boy Golf Carts - Lecanto",
    street: "299 East Gulf to Lake Highway",
    city: "Lecanto",
    state: "Florida",
    stateCode: "FL",
    zip: "34461",
    county: "Citrus County",
    lat: 28.8517,
    lng: -82.4876,
    region: "Nature Coast / Central West Florida",
    metro: "Homosassa Springs, FL MSA",
    dma: "Tampa-St. Petersburg DMA (partial)",
    serviceRadius: "60+ miles",
    population: "700,000+ (Nature Coast / North Tampa region)",
    targetMarkets: "Retirement communities, 55+ communities, golf communities, snowbird properties, RV parks",
    landmarks: "Crystal River National Wildlife Refuge, Homosassa Springs Wildlife State Park, Withlacoochee State Trail, The Villages (40 mi), Rainbow Springs State Park",
    interstate: "US-19, US-41, Route 44, I-75 (20 mi east)",
    nearbyCities: ["Crystal River", "Inverness", "Homosassa", "Homosassa Springs", "Beverly Hills", "Citrus Springs", "Pine Ridge", "Hernando", "Floral City", "Dunnellon", "Ocala", "Brooksville", "Spring Hill", "Weeki Wachee", "Hudson", "New Port Richey", "Bushnell", "Wildwood", "The Villages", "Lady Lake", "Leesburg", "Clermont", "Tavares", "Eustis", "Mount Dora"],
    nearbyCounties: ["Citrus", "Marion", "Levy", "Sumter", "Hernando", "Pasco", "Lake"],
    keywords: ["golf carts lecanto fl", "golf carts citrus county fl", "golf carts crystal river fl", "golf carts inverness fl", "golf carts homosassa fl", "golf carts nature coast florida", "golf carts near the villages fl", "golf carts ocala fl", "golf carts spring hill fl", "golf carts hernando county fl", "golf cart dealer central florida", "golf carts 55+ communities florida", "golf carts retirement communities florida", "golf carts florida gulf coast"],
  },
];

export const SERVICE_STATES = Array.from(
  new Map(STORE_LOCATIONS.map((l) => [l.stateCode, l.state])).entries(),
).map(([code, name]) => ({ code, name }));

export function locationBySlug(slug: string): StoreLocation | undefined {
  return STORE_LOCATIONS.find((l) => l.slug === slug);
}
